matrix:
  include:
    - language: node_js
      node_js:
        - "stable"
      before_install:
        - cd FrontEnd/
      cache:
        directories:
        - node_modules
      script:
        - npm test

    - language: python
      before_install:
        - cd BackEnd/
      install: 
        - pip install -r requirements.txt
      script:
        - python test.py